### ISSUE TITLE
Choose roles

### ISSUE THREAD

**Issue by raspearsy** [raspearsy/bme590hrm#2]
Garren and I met and created the preliminary work structure below, splitting the project up between 4 roles. These roles are up for revision as work will not be evenly distributed over them in their current state. Please comment on this issue claiming a role or proposing an alternative work structure.

Input
Unit Testing
Code
Output

**Comment by gaa37** [comment]
To expand:
Input: Write a fxn that can take any CSV file and format it to remove the header file, leaving a 2 column array for the Code person to use. This person should also be responsible for developing the overall structure of the project (different I/O for each portion) so that we are all on the same page with our fxn calls.

Unit Testing: Pretty self-explanatory, work with other members to determine what the tests should be (and should be testing everyone exceptions in their code as well)

Code: Write the script to determine HR, long-term HR, and any brady/tachycardias

Output:  Make a fxn that will create the output of the file as specified in the assignment, including "closing the program gracefully" 

Again, this isn't the end-all be-all structure and is definitely up for discussion.

**Comment by jkhani** [comment]
I can get started on the Output role. We can reassess the relative workload for each role after giving it a shot. I'd say we plan to work on our respective parts this Sunday/Monday, then get together Tuesday to see where we could help each other. After class would be a good time for me.

**Comment by gaa37** [comment]
Nisarg is doing Input.

I can take the main coding aspect, leaving Ry🐶 as the unit test guy. I personally have an OH I have to attend right after class, but will make sure to push up code and be on the same page with you guys then. I can only assume he'll give us sufficient class time to work on it as well.

**Comment by nisargmshah** [comment]
I will work on the input function as well as developing the overall structure and will get this done by Monday. I also can't meet after class, but we should be able to discuss in class like Garren said. We can also meet later in the evening on Tuesday or sometime Wednesday to help each other as needed and to review the assignment.
